definitions:
  models.CreateChannelRes:
    properties:
      id:
        example: 66cd5b0d-4f91-43a6-96b0-f2ae9e3863d1
        type: string
    type: object
  models.HTTPError:
    properties:
      error:
        type: string
    type: object
  models.HTTPSuccess:
    properties:
      success:
        example: true
        type: boolean
    type: object
host: localhost
info:
  contact: {}
  description: This is a swagger specification for video-chat server backend.
  title: vide-chat API
  version: "1.0"
paths:
  /:
    get:
      description: Return a message about the service using the service name from
        configuration
      produces:
      - text/plain
      responses:
        "200":
          description: This is a service 'service_name'
          schema:
            type: string
      summary: Return a message about the service
      tags:
      - common
  /channels:
    post:
      description: Create new channel.
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/models.CreateChannelRes'
        "500":
          description: Cannot create channel
          schema:
            $ref: '#/definitions/models.HTTPError'
      summary: Create new channel
      tags:
      - channels
  /channels/{id}:
    get:
      description: Join to channel.
      parameters:
      - description: Channel ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "101":
          description: WebSocket Protocol Switch
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.HTTPError'
      summary: Join to channet
      tags:
      - channels
  /health:
    get:
      description: Return a success response indicating that the service is healthy
      produces:
      - application/json
      responses:
        "200":
          description: All good
          schema:
            $ref: '#/definitions/models.HTTPSuccess'
      summary: Return a health check response
      tags:
      - common
securityDefinitions:
  ApiKeyAuth:
    description: Used for secure private routes
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
